### ISSUE TITLE
License for content?

### ISSUE THREAD

**Issue by a3nm** [arxivwiki/arxivwiki#66]
Hello,

I was interested by the project but was unable to determine the license that applies to the content. In this light, it's not even clear that you can redistribute modifications.

Would it make sense to have an explicit open license, e.g., the Creative Commons BY-SA license that Wikipedia uses? https://creativecommons.org/licenses/by-sa/4.0/

I hope this helps!

**Comment by marwahaha** [comment]
I'm comfortable with CC-BY, or maybe even CC0 so attribution isn't required.

**Comment by a3nm** [comment]
Sounds good! If you want to do this, it should probably be visible on the wiki itself and in the repository. Further, you'd want users who contribute to the wiki to agree to this (the way Wikipedia does), and if any users had already contributed content you'd need their permission to relicense.

I hope this helps -- this was just a suggestion of course, feel free to do what you want with it. :)
